import os
import json
import logging
from firmwell.backend.call_chain_utils.GhidraTool import GhidraTool

logger = logging.getLogger(__name__)


class NvramAnalyzer:
    def __init__(self, firm_name, config=None):
        self.firm_name = firm_name
        self.config = config

        # Ghidra configuration - similar to CallChainConstructor
        self.HEADLESS_ANALYZER = "/ghidra_11.2_PUBLIC/support/analyzeHeadless"
        self.GHIDRA_SCRIPT = "/fw/firmwell/backend/call_chain_utils/nvram_extract.py"

        # Setup project paths
        firm_dir = os.path.join("/tmp", self.firm_name)
        self.ghidra_proj_path = os.path.join(firm_dir, "ghidra_nvram_project")
        if not os.path.exists(self.ghidra_proj_path):
            os.makedirs(self.ghidra_proj_path)
        
        self.ghidra_result_path = os.path.join(firm_dir, "ghidra_nvram_result")
        if not os.path.exists(self.ghidra_result_path):
            os.makedirs(self.ghidra_result_path)

    def run_ghidra_nvram_analysis(self, binary_path: str):
        ghidra_tool = GhidraTool(project_path=self.ghidra_proj_path,
                                 project_name=self.firm_name,
                                 result_path=self.ghidra_result_path,
                                 ghidra_script=self.GHIDRA_SCRIPT,
                                 headless_analyzer=self.HEADLESS_ANALYZER)

        try:
            # For nvram analysis, we pass the result_path as target_str 
            # since nvram_extract.py expects result_path as first argument
            ghidra_tool.run(binary_path, self.ghidra_result_path)
        finally:
            ghidra_tool.stop_ghidra_process()

    def get_nvram_data_from_result(self, binary_path: str):
        """
        Read the NVRAM analysis results from the JSON file generated by nvram_extract.py
        and convert it to key -> first_value format as requested.
        """
        binary_name = os.path.basename(binary_path)
        result_file = os.path.join(self.ghidra_result_path, binary_name + "_nvram.json")
        
        if not os.path.exists(result_file):
            logger.warning(f"NVRAM result file not found: {result_file}")
            return {}
        
        try:
            with open(result_file, 'r') as f:
                nvram_data = json.load(f)
            
            # Convert from key -> [multiple_values] to key -> first_value format
            simplified_nvram_data = {}
            for key, values in nvram_data.items():
                if values and len(values) > 0:
                    # Take the first value as requested
                    simplified_nvram_data[key] = values[0]
                    logger.debug(f"NVRAM: {key} = {values[0]} (from {len(values)} possible values)")
            
            return simplified_nvram_data
            
        except Exception as e:
            logger.error(f"Error reading NVRAM result file {result_file}: {e}")
            return {}

    def analyze_binary(self, binary_path: str):
        """
        Main method to analyze a binary for NVRAM key-value pairs.
        
        Args:
            binary_path: Path to the binary file to analyze
            
        Returns:
            dict: NVRAM key-value pairs where each key maps to its first found value
        """
        if not os.path.exists(binary_path):
            logger.error(f"Binary file not found: {binary_path}")
            return {}
        
        logger.info(f"Starting NVRAM analysis for: {os.path.basename(binary_path)}")
        
        # Run Ghidra analysis
        self.run_ghidra_nvram_analysis(binary_path)
        
        # Get and process results
        nvram_data = self.get_nvram_data_from_result(binary_path)
        
        logger.info(f"NVRAM analysis completed. Found {len(nvram_data)} key-value pairs.")
        
        return nvram_data


def main():
    """
    Example usage of the NvramAnalyzer
    """
    import sys
    
    if len(sys.argv) < 3:
        print("Usage: python nvram_infer.py <firm_name> <binary_path> [additional_binary_paths...]")
        print("Example: python nvram_infer.py test_firmware /path/to/httpd /path/to/other_binary")
        return
    
    firm_name = sys.argv[1]
    binary_paths = sys.argv[2:]
    
    # Setup logging
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    
    # Create analyzer
    analyzer = NvramAnalyzer(firm_name)
    
    if len(binary_paths) == 1:
        # Analyze single binary
        nvram_data = analyzer.analyze_binary(binary_paths[0])
    
    # Print results
    print("\n" + "="*50)
    print("NVRAM Analysis Results:")
    print("="*50)
    
    if nvram_data:
        for key, value in nvram_data.items():
            print(f"{key}: {value}")
    else:
        print("No NVRAM data found.")
    
    # Save results to file
    output_file = f"/tmp/{firm_name}_nvram_summary.json"
    with open(output_file, 'w') as f:
        json.dump(nvram_data, f, indent=2)
    
    print(f"\nResults saved to: {output_file}")


if __name__ == "__main__":
    main()
